#include <iostream>
/*
				Task:
				2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/

int result(int range){
	int i = 0;
	int q = 1;
	int num=0;
	while (true) {
		if (i >=range || q >= range){
			break;
		}else{
			i+=q;
			q+=i;
			if (i%2==0){
				num+=i;
			}else if(q%2==0){
				num+=q;
			}
		}
	}
	return num;
}

int main(int argc, char const *argv[]) {
	int range = 4000000;
	std::cout << result(range) << '\n';
	return 0;
}
